### ISSUE TITLE
RuntimeError: Expected hidden size (1, 8, 512), got (8, 473, 1024)

### ISSUE THREAD

**Issue by tcxia** [andrew-r96/BertQuestionGeneration#4]
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    train_loss_epoch = BertTrain(model, device, train_loader, optimizer, criterion, clip)
  File "train.py", line 63, in BertTrain
    prediction = model([x.to(device) for x in input_data], output_data.to(device))
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/nlper/Bert_example/questionGen/model/seq2seq.py", line 47, in forward
    output, hidden = self.decoder(output, bert_encodings, hidden)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/nlper/Bert_example/questionGen/model/decoder.py", line 39, in forward
    output, hidden = self.rnn(embedded, queries)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 713, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 183, in check_forward_args
    self.check_hidden_size(hidden, expected_hidden_size)
  File "/root/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 176, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden size (2, 8, 512), got (8, 473, 1024)

**Comment by andrearosasco** [comment]
Nice traceback but it would be great if you could provide some additional information:
Which branch are you using? Did you modify config.py or any other file?

**Comment by tcxia** [comment]
> Nice traceback but it would be great if you could provide some additional information:
> Which branch are you using? Did you modify config.py or any other file?

Hi, using the master branch, and don't modify the config.py. But the squad dataset is a download by myself

**Comment by andrearosasco** [comment]
Hi sorry for taking so long to answer, I hope you managed to figure it out yourself in the meantime.

Anyway, as I've written in the readme you should use the other branch, alt-attention, because it has a better implementation of attention (I'll make that branch the main one when I have more time). 

I cloned the master branch, installed the required packages and run main.py without any problem so I guess that it has something to do with you downloading SQuAD by yourself. The code doesn't just download SQuAD but it also preprocesses it to work for question generation (normally it's a question answering dataset). If you want to use your own dataset you should also take care of the preprocessing.
